#!/bin/bash

# Declare an empty array to store the filenames
filenames=()

# Iterate through the filenames and add each one to the array
for filename in 0-list_databases.sql 11-best_score.sql 3-list_tables.sql 9-full_creation.sql \
    1-create_database_if_missing.sql 12-no_cheating.sql 4-first_table.sql README.md \
    10-top_score.sql 13-change_class.sql 4-full_first_table.sql gitx \
    100-move_to_utf8.sql 14-average.sql 5-full_table.sql lists \
    101-avg_temperatures.sql 15-groups.sql 6-list_values.sql \
    102-top_city.sql 16-no_link.sql 7-insert_value.sql \
    103-max_state.sql 2-remove_database.sql 8-count_89.sql
do
    filenames+=("$filename")  # Append the filename to the array
done

# create commits
echo "Filenames:"
for filename in "${filenames[@]}"
do
    git add $filename
    git commit -m "update $filename"
done

