#!/bin/bash

read -p "Enter file name to test : " filename

pycodestyle --first $filename

num_lines=$(pycodestyle --first $filename | wc -l)


if [ $num_lines != 0 ]; then
	read -p "Continue to know specific error line and more details (y or n): " choice

	if [ $choice == "y" ]; then
        	pycodestyle --show-source --show-pep8 $filename
	fi
else
	echo "Successfully checked, no errors found"
fi
